spring:
  datasource:
    url: jdbc:h2:mem:local
    driver-class-name: org.h2.Driver
    username: sa
  h2:
    console:
      enabled: true
  exposed:
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379