CREATE TABLE IF NOT EXISTS BRANDS
(
    ID     BIGINT AUTO_INCREMENT PRIMARY KEY,
    "NAME" VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS CATEGORIES
(
    ID     BIGINT AUTO_INCREMENT PRIMARY KEY,
    "NAME" VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUCTS
(
    ID          BIGINT AUTO_INCREMENT PRIMARY KEY,
    CATEGORY_ID BIGINT         NOT NULL,
    BRAND_ID    BIGINT         NOT NULL,
    "NAME"      VARCHAR(255)   NOT NULL,
    AMOUNT      DECIMAL(10, 2) NOT NULL
);